[technote]
id = "SOTN-012"
series_id = "SOTN"
canonical_url = "https://sotn-012.lsst.io"
github_url = "https://github.com/lsst-so/sotn-012"
github_default_branch = "main"
date_created = 2026-09-23T23:03:29Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Bruno C."
name.family = "Quint"
internal_id = "quintb"
orcid = "https://orcid.org/0000-0002-1557-3560"
[[technote.authors.affiliations]]
name = "NSF-DOE Vera C. Rubin Observatory / NSF NOIRLab"
internal_id = "RubinObsC"
address = "La Serena"

[[technote.authors]]
name.given = "Erik"
name.family = "Dennihy"
internal_id = "dennihye"
orcid = "https://orcid.org/0000-0003-2852-268X"
[[technote.authors.affiliations]]
name = "NSF-DOE Vera C. Rubin Observatory"
internal_id = "RubinObs"
